apiVersion: apps/v1
kind: Deployment
metadata:
  name: demo
  labels:
    app: demo
spec:
  replicas: 1
  selector:
    matchLabels:
      app: demo
  template:
    metadata:
      labels:
        app: demo 
    spec:
      containers: 
        - name: demo
          image: localhub/localhellogo
          imagePullPolicy: Never
          ports:
            - containerPort: 8888
          # env:                        # CASE I) takes one key (use GREETING in the code)
          #   - name: GREETING
          #     valueFrom:
          #       configMapKeyRef:
          #         name: app-config
          #         key: greetings

          # envFrom:                    # CASE II) takes all keys
          #   - configMapRef:
          #       name: app-config

          volumeMounts:                 # CASE III) env as volume
            - mountPath: /config/
              name: demo-config-volume
              readOnly: true
      
      volumes:  # Volume for CASE III
      - name: demo-config-volume
        configMap:
          name: app-config
          items:
            - key: config
              path: app.yaml

