apiVersion: apps/v1
kind: Deployment
metadata:
  name: kafka-deployment
  labels:
    app: kafka-cluster
    delete: kafka-bro
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      containers:      
      - name: kafka-cont
        image: confluentinc/cp-kafka:7.3.0
        # ports:
        # - containerPort: 9092
        env:
          - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
            value: "1"
          - name: KAFKA_BROKER_ID
            value: "1"
          - name: KAFKA_ZOOKEEPER_CONNECT
            value: "zoo:2181"
          - name: KAFKA_ADVERTISED_LISTENERS
            value: "PLAINTEXT://service-kafka:9092"
          - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
            value: "true"
            