apiVersion: v1
kind: Service
metadata:
  name: service-kafka         # FIX: avoid names starting with kafka [https://morioh.com/p/d1bafbd024d6]
  labels:
    app: kafka-cluster
spec:
  ports:
  - port: 9092
    name: kafka-port
    protocol: TCP
  selector:
    app: kafka-cluster
    # id: "0"
  type: LoadBalancer