apiVersion: apps/v1
kind: Deployment
metadata:
  name: zookeeper-deployment
  labels:
    app: kafka-cluster
spec:
  replicas: 1
  selector:
    matchLabels:
      app: kafka-cluster
  template:
    metadata:
      labels:
        app: kafka-cluster
    spec:
      containers:
      - name: zookeeper-cont
        image: confluentinc/cp-zookeeper
        ports:
        - containerPort: 2181
        env:
          - name: ZOOKEEPER_SERVER_ID
            value: "1"
          - name: ZOOKEEPER_CLIENT_PORT
            value: "2181"
      
      # - name: kafka-cont
      #   image: confluentinc/cp-kafka
      #   ports:
      #   - containerPort: 9092
        # env:
        #   - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
        #     value: 1
        #   - name: KAFKA_BROKER_ID
        #     value: 1
        #   - name: KAFKA_ZOOKEEPER_CONNECT
        #     value: zookeeper-cont:2181
        #   - name: KAFKA_ADVERTISED_LISTENERS
        #     value: PLAINTEXT://ksource:9092
        #   - name: KAFKA_CFG_AUTO_CREATE_TOPICS_ENABLE
        #     value: true
            